# It's better that these Travis files explicitly specify:
# sudo:false
# which then allows them to be run in a Docker-style container
# but this file currently having to use sudo to get a recent Boost (1.57.0) because
# the whitelisted boost-latest ppa respoistory:
# https://launchpad.net/~boost-latest/+archive/ubuntu/ppa
# currently only offers Boost <= v1.55.0.
# If/when Boost >= v1.57.0 gets added to boost-latest, then
# use that instead of the sudo commands and then uncomment sudo: false
#sudo: false
language: cpp

notifications:
  slack: cathupdate:9wDvWdLmrVhxI4JcsOFlkxir
  email:
    recipients:
      - i.sillitoe@ucl.ac.uk
      - t.lewis@ucl.ac.uk

compiler:
  - clang
  - gcc

install:
  - if [ "$CXX" == "g++"     ]; then export CXX="g++-4.9"     CC="gcc-4.9"   ; fi
  - if [ "$CXX" == "clang++" ]; then export CXX="clang++-3.6" CC="clang-3.6" ; fi

addons:
  apt:
    sources:
      - kalakris-cmake
      - llvm-toolchain-precise-3.6
      - ubuntu-toolchain-r-test
    packages:
      - clang-3.6
      - cmake
      - gcc-4.9
      - g++-4.9

before_script:
  - sudo add-apt-repository ppa:afrank/boost -y
  - sudo apt-get update -q
  - sudo apt-get install libboost1.57-all libboost1.57-all-dev
  - mkdir release_build
  - cd release_build
  - cmake -DCMAKE_BUILD_TYPE=RELEASE ..

script: make -k && ../build-test
