sudo: false
language: cpp

compiler:
 - clang
 - gcc

install:
 - if [ "$CXX" = "g++" ]; then export CXX="g++-4.9" CC="gcc-4.9"; fi
 
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - boost-latest
    packages:
    - cmake
    - gcc-4.9
    - g++-4.9
    - libboost1.55-all-dev

before_script:
 - mkdir release_build
 - cd release_build
 - cmake -DCMAKE_BUILD_TYPE=RELEASE ..

script: make && ../build-test
