language: cpp

compiler:
 - clang
 - gcc

before_script:
 - sudo apt-get update -qq
 - sudo apt-get install libboost-dev
 - mkdir release_build
 - cd release_build
 - cmake -DCMAKE_BUILD_TYPE=RELEASE ..

script: make && ../build-test
