language: cpp

sudo: false

compiler:
 - clang
 - gcc
 
addons:
  apt:
    packages:
     - libboost-dev
     - cmake

before_script:
 - mkdir release_build
 - cd release_build
 - cmake -DCMAKE_BUILD_TYPE=RELEASE ..

script: make && ../build-test
