site_name: cath-tools
theme: readthedocs

nav:
- Home                  : index.md
- Tools :
  - cath-cluster        : tools/cath-cluster.md
  - cath-map-clusters   : tools/cath-map-clusters.md
  - cath-resolve-hits   : tools/cath-resolve-hits.md
  - cath-ssap           : tools/cath-ssap.md
  - cath-superpose      : tools/cath-superpose.md
- Build                 : build.md
- License               : license.md
- References            : references.md

extra_css: [mkdocs_extra.css]
