name: CMake

# TODO:
#  * UBSan/ASan (ASAN_OPTIONS="detect_container_overflow=0" on mac? `-fuse-ld=gold` for Linux GCC sanitizer?)?
#  * Clang (libc++-dev libc++1 libc++abi-dev)?
#  * Windows?

on: [push, pull_request]

env:
  BUILD_EXTRA_CATH_TESTS: ON
  BUILD_EXTRA_CATH_TOOLS: ON

jobs:
  build:
    strategy:
      matrix:
        compiler: [ clang ]
        flavour: [ release ]
        os: [ ubuntu-20.04, macos-10.15 ]

        include:
          - compiler: gcc
            flavour: release
            os: ubuntu-20.04

      fail-fast: false

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2

    - name: Setup (Ubuntu 20.04)
      if: matrix.os == 'ubuntu-20.04'
      env:
        # Prevents the apt-get of the tzdata package hanging on an interactive user prompt
        DEBIAN_FRONTEND: noninteractive
      run: sudo apt-get update && sudo apt-get install -y cmake git libboost-dev libboost-filesystem-dev libboost-iostreams-dev libboost-log-dev libboost-program-options-dev libboost-test-dev libboost-timer-dev libgsl-dev ninja-build

    - name: Setup (Ubuntu 20.04 - Clang)
      if: matrix.os == 'ubuntu-20.04' && matrix.compiler == 'clang'
      run: sudo apt-get update && sudo apt-get install -y clang libc++-dev libc++1 libc++abi-dev

    - name: Setup (Ubuntu 20.04 - GCC)
      if: matrix.os == 'ubuntu-20.04' && matrix.compiler == 'gcc'
      run: sudo apt-get update && sudo apt-get install -y g++-10

    - name: Setup (MacOS 10.15)
      if: matrix.os == 'macos-10.15'
      run: brew update && brew install boost gsl ninja

    - name: Create build directory
      run: cmake -E make_directory ${{github.workspace}}/build

    - name: Configure CMake
      shell: bash
      run: cmake -GNinja "-B$GITHUB_WORKSPACE/build" "-S$GITHUB_WORKSPACE" "-DCMAKE_TOOLCHAIN_FILE=$GITHUB_WORKSPACE/.github/cmake-toolchain-files/${{ matrix.os }}.${{ matrix.compiler }}.${{ matrix.flavour }}.cmake"

    - name: Build
      shell: bash
      run: ninja -C "$GITHUB_WORKSPACE/build" -k 0

    - name: Grab version info from example executable
      shell: bash
      run: ${GITHUB_WORKSPACE}/build/bin/cath-superpose --version

    - name: Test
      working-directory: ${{github.workspace}}/build
      shell: bash
      run: ctest --output-on-failure

    - name: Move executables to add OS suffix to their names
      shell: bash
      run: find "$GITHUB_WORKSPACE/build/bin" -type f -exec mv {} {}.${{ matrix.os }} \;

    - name: Publish to release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/') && matrix.flavour == 'release' && ( ( matrix.os == 'macos-10.15' && matrix.compiler == 'clang' ) || ( matrix.os == 'ubuntu-20.04' && matrix.compiler == 'gcc' ) )
      with:
        files: |
          "$GITHUB_WORKSPACE/build/bin/cath-assign-domains.${{ matrix.os }}"
          "$GITHUB_WORKSPACE/build/bin/cath-cluster.${{ matrix.os }}"
          "$GITHUB_WORKSPACE/build/bin/cath-map-clusters.${{ matrix.os }}"
          "$GITHUB_WORKSPACE/build/bin/cath-refine-align.${{ matrix.os }}"
          "$GITHUB_WORKSPACE/build/bin/cath-resolve-hits.${{ matrix.os }}"
          "$GITHUB_WORKSPACE/build/bin/cath-ssap.${{ matrix.os }}"
          "$GITHUB_WORKSPACE/build/bin/cath-superpose.${{ matrix.os }}"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
